### PR TITLE
Cite just published bh2022 report

### PR DESCRIPTION
**Pull request by egonw**
And a few other suggestions

### CODE REVIEW

**Comment by arunisaac** [comment]
Hi Egon,

I'm not sure why I have been assigned to this PR. What do I need to do?

Regards,
Arun

**Comment by egonw** [comment]
> I'm not sure why I have been assigned to this PR.

You were listed as first author, that's all. Who is going to take this article forward and submit it?

**Comment by arunisaac** [comment]
Ah, sorry, I didn't realize I was named the first author. I will check
with Pjotr and get back to you.

**Comment by arunisaac** [comment]
Sorry, I thought this PR was about the 2022 paper. I saw 2022 in the
title, didn't read carefully, and got confused. I am indeed the first
author of the 2023 paper. I will take it forward.

**Pull request merged**
